services:
    pg:
        image: postgres:17.9
        restart: unless-stopped
        ports:
            - "7075:5432"
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=teste-starti
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - ntwrk

networks:
    ntwrk:
        driver: bridge

volumes:
    postgres_data:
